### PR TITLE
:construction_worker: Try using the rocker/tidyverse image again

### PR DESCRIPTION
**Pull request by jonmcalder**
@ErikSchierboom Let's give this approach a try again and see if maybe it works now that both the Exercism stack (docker version etc) and this docker image itself are a lot more recent. 

But please be ready to revert soon after you merge this because though much has changed since we last tried the outcome could still be the same 😁

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I'm off until Tuesday, but I'll do it then. Could you fix ci maybe? And do you have code that used to not work and now will?

**Comment by jonmcalder** [comment]
Sorry yes - I was actually just looking at the CI failure which is unrelated to this. 

Should I address that in a separate PR? I think the CI failure is due to updates in {testthat} which mean the expected failure message needs to be updated for one of the test cases.

**Comment by ErikSchierboom** [comment]
A separate pr would be my preferred approach, yes

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Let's see how this goes!

**Comment by ErikSchierboom** [comment]
@jonmcalder Success!

image

**Comment by jonmcalder** [comment]
Thank you so much @ErikSchierboom. Finally!

**Comment by ErikSchierboom** [comment]
Thank you!

**Pull request merged**
